[project]
name = "map-tool-api"
version = "0.1.0"
description = "API for my thesis app"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bcrypt>=5.0.0",
    "dotenv>=0.9.9",
    "fastapi[standard]>=0.116.1",
    "passlib>=1.7.4",
    "pyjwt>=2.10.1",
    "pymongo>=4.15.0",
]
